#!/usr/bin/env bash
# Redirection
apt-get update
apt-get install -y nginx
echo "Hello World!" > /var/www/html/index.nginx-debian.html

text="server {
    listen 80;
    server_name example.com;

    location /redirect_me {
        return 301 https://www.youtube.com/watch?v=QH2-TGUlwu4;
    }
}"

echo "${text}" > /etc/nginx/sites-available/default
service nginx restart
