#!/usr/bin/env bash
# Redirection
apt-get update
apt-get install -y nginx
echo $'Ceci n\'est pas une page\n' > /home/ubuntu/404.html

text="# Comment \n\terror_page 404 /404.html;\n\tlocation = /404.html {\n\t\troot /home/ubuntu;\n\t\tinternal;\n\t}\n\n\n"

sed -i -e "22 i ${text}" /etc/nginx/sites-enabled/default

service nginx restart
