#!/usr/bin/env bash
# Double the number of webservers
# /var/www/html/index.nginx-debian.html
# /etc/nginx/sites-available/default

X_Served_By='web-01'

apt-get update
apt-get install -y nginx

echo "Hello World!" > /var/www/html/index.nginx-debian.html
echo "Ceci n'est pas une page" > /var/www/html/404.html


config="
server {
    # Robot added==============================
        location /redirect_me {
        return 301 https://www.youtube.com/watch?v=QH2-TGUlwu4;
        }

        error_page 404 /404.html;
        location = /404.html {
                root /var/www/html;
                internal;
        }
    # Add end======================================



    listen 80 default_server;
    listen [::]:80 default_server;

    root /var/www/html;

    # Add index.php to the list if you are using PHP
    index index.html index.htm index.nginx-debian.html;

    server_name _;

    location / {
        # First attempt to serve request as file, then
        # as directory, then fall back to displaying a 404.

        # Robot added==================================
        add_header X-Served-By ${X_Served_By};
        # Add end======================================
        try_files \$uri \$uri/ =404;
    }
}"


echo "${config}" > /etc/nginx/sites-available/default


# echo "${config}"

service nginx restart
