#!/usr/bin/env bash
# Install your load balancer
# Resource: https://www.stackpath.com/blog/load-balancing-haproxy
# 			https://youtu.be/tl8movPZbJM
# /etc/default/haproxy
# /etc/haproxy/haproxy.cfg

# Install HAproxy load blancer
apt-get install -y --no-install-recommends software-properties-common
add-apt-repository -y  ppa:vbernat/haproxy-2.4
apt-get install -y haproxy=2.4.\*

# Enable init script
echo "ENABLED=1" >> /etc/default/haproxy

config="
backend web-backend
    balance roundrobin
    mode tcp

    server web1 52.207.157.20:80 check
    server web2 54.175.3.48:80 check

frontend http
    bind *:80
    mode tcp
     
    default_backend web-backend
"


echo "${config}" >> /etc/haproxy/haproxy.cfg

service haproxy restart
